
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AosInit from './_components/AosInit';

const poppins = Poppins({
  weight: ['100', '300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${poppins.className}`}>
      <body>
        {children}
        <AosInit />
      </body>
    </html>
  );
}
